# Generated by Django 4.1.7 on 2023-03-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect', models.CharField(max_length=50)),
                ('job_tittle', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=50)),
            ],
        ),
    ]
